### ISSUE TITLE
where can find the test_asr.json?

### ISSUE THREAD

**Issue by igorhuangchao** [kolk/MODELING-ASR-AMBIGUITY-FOR-NEURAL-DIALOGUE-STATE-TRACKING-USING-WORD-CONFUSION-NETWORKS#2]
hello,
    I try to  train the model with asr, but I get an error which couldn't find the test_asr.json file. 
as I see,  if we want train the model with confusion network, We need preprocessing the dstc2 dateset.
so could your offer the preproceed dstc2 data. 

thanks.

**Comment by igorhuangchao** [comment]
or could you share the preprocess_dstc file. I guess you forget it.   

thanks for your contributions.

**Comment by kolk** [comment]
Please find the preprocessed files at: https://drive.google.com/drive/folders/1mobS_1vmB4pJCtmD84QIIOObfdwwawlR?usp=sharing
